Repository Simple2B/BeamSuntory, pull requests merged in 2023-10, with the labels that each got.

#326 Andrii/feature/event multiple groups
  app/models/cart.py
  app/models/report_inventory.py
  app/schema/cart.py
  app/static/css/styles.css
  app/static/js/adjust.js
  app/static/js/assign.js
  app/static/js/base.js
  app/static/js/bell.js
  app/static/js/cart.js
  app/static/js/delivery_agent.js
  app/static/js/division.js
  app/static/js/event.js
  app/static/js/group.js
  app/static/js/group_for_product.js
  app/static/js/inbound_order.js
  app/static/js/incoming_stock.js
  app/static/js/inventory.js
  app/static/js/master_group.js
  app/static/js/master_group_for_product.js
  app/static/js/outgoing_stock.js
  app/static/js/pickup_inbound.js
  app/static/js/pickup_order.js
  app/static/js/product.js
  app/static/js/report_adjustment.js
  app/static/js/report_assign.js
  app/static/js/report_event.js
  app/static/js/report_inbound_orders.js
  app/static/js/report_inventory.js
  app/static/js/report_share_request.js
  app/static/js/report_shipping.js
  app/static/js/request_share.js
  app/static/js/ship_request.js
  app/static/js/store.js
  app/static/js/store_category.js
  app/static/js/supplier.js
  app/static/js/user.js
  app/static/js/warehouse.js
  app/templates/cart.html
  app/templates/product/products.html
  app/templates/request_share/request_shares.html
  app/views/cart.py
  app/views/outgoing_stock.py
  app/views/product.py
  app/views/request_share.py
  app/views/ship_request.py
  migrations/versions/6278e53df31e_cart_change_group_format_data.py
  src/cart.ts
  src/product.ts
  tests/conftest.py
  tests/test_cart.py
Labels: enhancement

#334 Petro/feature/report SKU
  app/models/__init__.py
  app/models/adjust.py
  app/models/assign.py
  app/models/report_sku.py
  app/schema/__init__.py
  app/schema/filter_report_inventories.py
  app/schema/report_sku.py
  app/static/js/report_inventory.js
  app/static/js/report_sku.d.ts
  app/static/js/report_sku.js
  app/templates/report/sku/reports_table.html
  app/templates/report/sku/skus.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/inbound_order.py
  app/views/incoming_stock.py
  app/views/outgoing_stock.py
  app/views/pickup_inbound.py
  app/views/product.py
  app/views/report_sku.py
  app/views/request_share.py
  app/views/ship_request.py
  migrations/versions/943a9c8ca92f_report_sku.py
  migrations/versions/975158512966_report_sku_adjust_to_adjusy_qty.py
  src/report_inventory.ts
  src/report_sku.ts
  webpack.config.js
Labels: enhancement

#359 fix report adjustment
  app/static/js/report.js
  app/templates/report/adjustment/reports_table.html
  src/report.ts
Labels: bug

#358 Petro/fix/inventory report del view
  app/templates/report/inventory/reports_table.html
  app/templates/sidebar.html
Labels: enhancement

#343 Petro/feature/shelf life report
  app/controllers/report/report.py
  app/controllers/report/report_shelf_life.py
  app/schema/__init__.py
  app/schema/filter_report_inventories.py
  app/schema/product_allocated.py
  app/schema/report.py
  app/static/js/report.js
  app/static/js/report_inventory.js
  app/static/js/report_shelf_life.d.ts
  app/static/js/report_shelf_life.js
  app/static/js/types.d.ts
  app/templates/report/index.html
  app/templates/report/shelf_life/reports_table.html
  app/templates/report/shelf_life/shelf_lifes.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/incoming_stock.py
  app/views/pickup_order.py
  app/views/report_shelf_life.py
  src/report.ts
  src/report_inventory.ts
  src/report_shelf_life.ts
  src/types.ts
  webpack.config.js
Labels: enhancement

#374 save images
  .gitignore
  app/__init__.py
  app/controllers/__init__.py
  app/controllers/image.py
  app/forms/product.py
  app/models/__init__.py
  app/models/image.py
  app/models/product.py
  app/static/js/product.js
  app/templates/product/add.html
  app/templates/product/edit.html
  app/views/auth.py
  app/views/outgoing_stock.py
  app/views/product.py
  docker-compose.prod.yml
  migrations/versions/9c3b30484072_images_table.py
  poetry.lock
  pyproject.toml
  src/product.ts
  tests/test_products.py
Labels: enhancement

#391 Petro/fix/image permissions shelf life
  .gitignore
  app/controllers/user.py
  app/schema/product_allocated.py
  app/views/product.py
  app/views/user.py
Labels: bug, enhancement

#396 Petro/feature/upload available qty
  app/forms/product.py
  app/templates/product/upload.html
  app/views/product.py
Labels: enhancement

#395 fix event adjust, add group to event model, refactor product entity
  app/forms/product.py
  app/models/event.py
  app/models/product.py
  app/schema/__init__.py
  app/schema/event.py
  app/schema/product.py
  app/static/js/product.js
  app/static/js/report_sku.js
  app/views/event.py
  app/views/inventory.py
  app/views/product.py
  app/views/ship_request.py
  migrations/versions/ed00960cfc58_event_add_group.py
  src/product.ts
Labels: bug

#397 Andrii/fix/adjust product events
  app/schema/__init__.py
  app/schema/product.py
  app/views/product.py
  tests/conftest.py
  tests/test_adjustment.py
Labels: bug

#398 protect to delete/edit main roles, check for underscore in groups
  app/__init__.py
  app/controllers/__init__.py
  app/controllers/utils.py
  app/forms/group.py
  app/forms/group_for_product.py
  app/schema/user.py
  app/templates/division/divisions.html
  app/views/division.py
  app/views/master_group.py
  app/views/master_group_for_product.py
  tests/test_devision.py
Labels: bug

#403 Petro/feature/csv add groups
  app/commands/__init__.py
  app/controllers/image.py
  app/models/__init__.py
  app/models/user.py
  app/models/values.py
  app/schema/filter_report_inventories.py
  app/static/img/no_picture_default.png
  app/static/img/product/no_picture_default.png
  app/templates/product/upload.html
  app/views/cart.py
  app/views/product.py
  migrations/versions/47b50647a3cb_remove_values.py
Labels: enhancement

#404 Petro/fix/products upload
  .github/workflows/python-app.yml
  app/__init__.py
  app/controllers/__init__.py
  app/controllers/utils.py
  app/templates/product/upload.html
  app/views/product.py
  tests/conftest.py
  tests/data/All Products part 5.csv
  tests/test_products.py
Labels: bug

#415 upload product groups datalist
  app/controllers/__init__.py
  app/controllers/utils.py
  app/models/user_group.py
  app/static/js/base.js
  app/static/js/incoming_stock.js
  app/static/js/report_adjustment.js
  app/static/js/report_event.js
  app/static/js/report_inventory.js
  app/static/js/report_share_request.js
  app/static/js/report_shipping.js
  app/templates/product/upload.html
  app/views/product.py
  app/views/user.py
  src/base.ts
Labels: enhancement

#416 add available qty to assign
  .vscode/settings.json
  app/controllers/__init__.py
  app/controllers/utils.py
  app/static/js/product.js
  app/templates/product/assign.html
  app/views/product.py
  app/views/request_share.py
  src/product.ts
Labels: bug

#417 lock previous days inbound order modals
  .vscode/settings.json
  app/forms/inbound_order.py
  app/schema/product_allocated.py
  app/static/js/inbound_order.js
  app/templates/inbound_order/add.html
  app/templates/inbound_order/edit.html
  src/inbound_order/inbound_order.ts
  src/inbound_order/utils.ts
  tests/test_inbound_order.py
  tests/test_report_inbound_order.py
Labels: enhancement

#418 show info about current warehouse_products in inventory reports
  app/controllers/report/report_inventory.py
  app/models/warehouse_product.py
  app/schema/__init__.py
  app/schema/report_inventory.py
  app/templates/report/inventory/reports_table.html
  migrations/versions/71314055728b_created_at_for_warehouse_product.py
Labels: enhancement

#419 default group for inbound order edit modal
  app/static/js/inbound_order.js
  src/inbound_order/edit.ts
Labels: enhancement

#420 Petro/feature/datalist for groups
  app/static/js/inbound_order.js
  app/static/js/product.js
  app/templates/inbound_order/edit.html
  app/templates/product/assign.html
  app/views/inbound_order.py
  src/inbound_order/edit.ts
  src/product.ts
Labels: enhancement
