Repository Simple2B/BeamSuntory, pull requests merged in 2023-09, with the labels that each got.

#226 Petro/feature/notes for inbound order
  app/commands/__init__.py
  app/forms/__init__.py
  app/forms/inbound_order.py
  app/models/inbound_order.py
  app/schema/inbound_order.py
  app/static/js/adjust.js
  app/static/js/assign.js
  app/static/js/base.js
  app/static/js/bell.js
  app/static/js/cart.js
  app/static/js/delivery_agent.js
  app/static/js/division.js
  app/static/js/event.js
  app/static/js/group.js
  app/static/js/group_for_product.js
  app/static/js/inbound_order.js
  app/static/js/inbound_order/types.d.ts
  app/static/js/incoming_stock.js
  app/static/js/inventory.js
  app/static/js/master_group.js
  app/static/js/master_group_for_product.js
  app/static/js/outgoing_stock.js
  app/static/js/pickup_inbound.js
  app/static/js/pickup_order.js
  app/static/js/product.js
  app/static/js/request_share.js
  app/static/js/ship_request.js
  app/static/js/store.js
  app/static/js/store_category.js
  app/static/js/supplier.js
  app/static/js/user.js
  app/static/js/warehouse.js
  app/templates/incoming_stock/view.html
  app/templates/pickup_inbound/view.html
  app/views/incoming_stock.py
  app/views/pickup_inbound.py
  migrations/versions/8bf135cbedb5_added_user_to_event.py
  migrations/versions/cea2e3a205eb_wm_and_da_notes_to_inbound_order.py
  src/inbound_order/types.ts
  src/incoming_stock.ts
  src/pickup_inbound.ts
  src/product.ts
Labels: enhancement

#224 Andrii/fix/events cart calendar
  Dockerfile
  app/commands/__init__.py
  app/forms/ship_request.py
  app/models/event.py
  app/schema/event.py
  app/static/js/cart.js
  app/static/js/event.d.ts
  app/static/js/event.js
  app/static/js/pickup_order.js
  app/static/js/product.js
  app/templates/cart.html
  app/templates/event/events.html
  app/templates/pickup_order/view.html
  app/views/cart.py
  app/views/event.py
  app/views/inventory.py
  app/views/product.py
  app/views/ship_request.py
  src/cart.ts
  src/event.ts
  src/pickup_order.ts
  src/product.ts
Labels: bug, enhancement

#228 Andrii/fix/event test
  app/models/product.py
  app/views/event.py
  app/views/product.py
Labels: bug

#236 product customize bug
  app/static/js/product.js
  app/views/product.py
  src/product.ts
  tests/conftest.py
  tests/test_products.py
Labels: bug

#245 Maryna/fix/stock target group admin
  app/schema/user.py
  app/static/css/styles.css
  app/static/js/user.js
  app/templates/_macros.html
  app/templates/inbound_order/edit.html
  app/views/group.py
  app/views/inbound_order.py
  app/views/incoming_stock.py
  app/views/outgoing_stock.py
  app/views/pickup_inbound.py
  app/views/pickup_order.py
  app/views/ship_request.py
  app/views/user.py
  src/user.ts
Labels: enhancement

#244 show only warehouse-events if enabled events
  app/static/js/cart.js
  app/static/js/product.js
  app/templates/cart.html
  app/views/event.py
  app/views/product.py
  app/views/ship_request.py
  src/cart.ts
  src/product.ts
  tests/conftest.py
  tests/test_cart.py
  tests/test_event.py
  tests/test_ship_request.py
  tests/test_warehouse.py
Labels: bug

#256 disable stock-by-me when events enabled
  app/static/js/product.js
  app/views/cart.py
  app/views/product.py
  src/product.ts
Labels: bug

#258 fix cart validation
  app/static/js/cart.js
  app/static/js/product.js
  app/templates/product/event.html
  src/cart.ts
  src/product.ts
Labels: bug

#270 Andrii/fix/pickup order da notes share lock button
  app/forms/ship_request.py
  app/models/request_share.py
  app/static/js/pickup_order.js
  app/templates/pickup_order/view.html
  app/templates/request_share/request_shares.html
  app/views/product.py
  app/views/request_share.py
  src/pickup_order.ts
Labels: bug

#275 add group from to share request
  app/templates/request_share/request_shares.html
  app/views/request_share.py
Labels: bug

#278 dont_allow_to_order_earlier_then_today
  .github/workflows/python-app.yml
  app/forms/inbound_order.py
  tests/test_inbound_order.py
Labels: bug

#277 Andrii/fix/cart count total available quantity
  app/schema/cart.py
  app/static/js/cart.js
  app/static/js/report_event.js
  app/templates/outgoing_stock/view.html
  app/templates/pickup_order/view.html
  migrations/versions/e81b0028c2a9_report_events.py
  src/cart.ts
  src/report_event.ts
Labels: bug

#288 move depleting process from ship request create to dispatch
  app/views/outgoing_stock.py
  app/views/ship_request.py
  tests/conftest.py
  tests/test_cart.py
  tests/test_outgoing_stock.py
Labels: bug

#290 Andrii/fix/action buttons to view order modals
  app/static/js/outgoing_stock.d.ts
  app/static/js/outgoing_stock.js
  app/static/js/pickup_order.js
  app/templates/inbound_order/edit.html
  app/templates/incoming_stock/view.html
  app/templates/outgoing_stock/edit.html
  app/templates/outgoing_stock/outgoing_stocks.html
  app/templates/outgoing_stock/view.html
  app/templates/pickup_order/pickup_orders.html
  app/templates/pickup_order/view.html
  app/views/outgoing_stock.py
  app/views/pickup_order.py
  src/outgoing_stock.ts
  src/pickup_order.ts
  tests/test_outgoing_stock.py
  tests/test_pickup_order.py
Labels: bug

#293 Report event store column
  app/models/cart.py
  app/models/event.py
  app/models/report_event.py
  app/models/ship_request.py
  app/schema/__init__.py
  app/schema/cart.py
  app/schema/event.py
  app/schema/report_event.py
  app/static/js/report_event.js
  app/templates/report/event/events.html
  app/templates/report/event/view.html
  app/views/__init__.py
  app/views/report_event.py
  app/views/ship_request.py
  app/views/user.py
  src/report_event.ts
  tests/conftest.py
Labels: enhancement

#301 Gleb/feature/htmx
  app/commands/__init__.py
  app/models/cart.py
  app/models/event.py
  app/models/product.py
  app/models/report_event.py
  app/models/ship_request.py
  app/models/warehouse.py
  app/models/warehouse_product.py
  app/schema/report_event.py
  app/static/css/styles.css
  app/static/js/htmx.d.ts
  app/static/js/lib/htmx.js
  app/static/js/report_event.js
  app/templates/base.html
  app/templates/icon/spinner.html
  app/templates/report/event/events.html
  app/templates/report/event/reports_table.html
  app/templates/report/event/view.html
  app/views/report_event.py
  project.env
  src/htmx.ts
  src/report_event.ts
Labels: enhancement

#306 added report adjustment
  .prettierrc.json
  app/models/adjust.py
  app/models/adjusts_group_qty.py
  app/models/product.py
  app/schema/__init__.py
  app/schema/adjust.py
  app/schema/adjust_group_quantity.py
  app/schema/filter_report_adjustments.py
  app/schema/group.py
  app/schema/group_for_product.py
  app/schema/report_adjustment.py
  app/static/css/styles.css
  app/static/js/adjust.js
  app/static/js/report_adjustment.d.ts
  app/static/js/report_adjustment.js
  app/static/js/report_assign.js
  app/static/js/report_event.js
  app/templates/adjust/adjusts.html
  app/templates/adjust/view.html
  app/templates/report/adjustment/adjustments.html
  app/templates/report/adjustment/reports_table.html
  app/templates/report/adjustment/view.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/product.py
  app/views/report_adjustment.py
  migrations/versions/a919bd570a83_adjust_add_user_product.py
  src/adjust.ts
  src/report_adjustment.ts
  src/report_event.ts
  tests/test_report_adjustment.py
  webpack.config.js
Labels: enhancement

#304 Inventory reports
  app/models/__init__.py
  app/models/inbound_order.py
  app/models/report_inventory.py
  app/models/ship_request.py
  app/schema/__init__.py
  app/schema/filter_report_inventories.py
  app/schema/product.py
  app/schema/report_inventory.py
  app/schema/warehouse_product.py
  app/static/js/inbound_order/types.d.ts
  app/templates/report/inventory/inventories.html
  app/templates/report/inventory/reports_table.html
  app/templates/report/inventory/view.html
  app/templates/request_share/request_shares.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/incoming_stock.py
  app/views/outgoing_stock.py
  app/views/product.py
  app/views/report_inventory.py
  app/views/request_share.py
  migrations/versions/9f27cfb15648_report_inventory.py
  src/inbound_order/types.ts
  src/report_inventory.ts
  tests/test_adjustment.py
  tests/test_incoming_stock.py
  tests/test_outgoing_stock.py
  tests/test_products.py
  webpack.config.js
Labels: enhancement

#310 add action update comments to outgoing stock
  app/static/js/outgoing_stock.js
  app/templates/outgoing_stock/edit.html
  app/templates/outgoing_stock/outgoing_stocks.html
  src/outgoing_stock.ts
Labels: bug

#311 fix customize view column
  app/static/css/styles.css
  app/static/js/product.js
  app/templates/product/products.html
  app/templates/report/adjustment/reports_table.html
  app/views/group.py
  src/product.ts
Labels: bug
