Repository Simple2B/BeamSuntory, pull requests merged in 2023-08, with the labels that each got.

#128 fix cart max quantity
  app/models/cart.py
  app/schema/cart.py
  app/static/js/cart.js
  app/templates/cart.html
  app/views/cart.py
  src/cart.ts
Labels: bug

#95 create divisions and add, edit modals
  app/__init__.py
  app/commands/__init__.py
  app/forms/__init__.py
  app/forms/division.py
  app/models/__init__.py
  app/models/division.py
  app/models/user.py
  app/schema/__init__.py
  app/schema/division.py
  app/static/js/division.d.ts
  app/static/js/division.js
  app/static/js/outgoing_stock.js
  app/templates/division/add.html
  app/templates/division/divisions.html
  app/templates/division/edit.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/division.py
  migrations/versions/dc061e0b3e6f_division_and_updates.py
  src/division.ts
  src/outgoing_stock.ts
  tests/conftest.py
  tests/test_devision.py
  webpack.config.js
Labels: enhancement

#127 Petro/feature/io product allocation
  app/forms/inbound_order.py
  app/models/__init__.py
  app/models/inbound_order.py
  app/models/io_allocate_product.py
  app/static/js/inbound_order.js
  app/templates/inbound_order/add.html
  app/templates/inbound_order/edit.html
  app/templates/product/add.html
  app/views/inbound_order.py
  app/views/product.py
  migrations/versions/d2fc80a195e3_io_allocate_product.py
  src/inbound_order.ts
  tests/test_inbound_order.py
Labels: enhancement

#137 Petro/fix/io products
  app/forms/inbound_order.py
  app/models/inbound_order.py
  app/schema/inbound_order.py
  app/static/js/inbound_order.js
  app/templates/inbound_order/add.html
  app/templates/inbound_order/edit.html
  app/templates/inbound_order/inbound_orders.html
  app/templates/inbound_order/view.html
  app/templates/inventory/inventories.html
  app/views/inbound_order.py
  migrations/versions/21e6ebb8daa3_remove_delivery_agent_from_io.py
  src/inbound_order.ts
  tests/conftest.py
  tests/test_inbound_order.py
Labels: bug

#147 edit modal outgoing stock, delete buttons in division, fix image store category
  app/commands/__init__.py
  app/forms/ship_request.py
  app/forms/store_category.py
  app/models/cart.py
  app/models/ship_request.py
  app/models/store.py
  app/models/store_category.py
  app/static/img/default_store_category.png
  app/static/js/cart.d.ts
  app/static/js/cart.js
  app/static/js/outgoing_stock.js
  app/static/js/ship_request.js
  app/templates/cart.html
  app/templates/division/divisions.html
  app/templates/outgoing_stock/edit.html
  app/templates/outgoing_stock/outgoing_stocks.html
  app/templates/outgoing_stock/view.html
  app/templates/product/products.html
  app/templates/ship_request/add.html
  app/templates/ship_request/ship_requests.html
  app/templates/store/stores.html
  app/templates/store_category/store_categories.html
  app/views/cart.py
  app/views/division.py
  app/views/outgoing_stock.py
  app/views/ship_request.py
  app/views/warehouse.py
  migrations/versions/ab2e0f8ae3a8_add_store_category_foreign_key_to_ship_.py
  migrations/versions/b4a77bf1c442_remove_warehouse_from_ship_request_add_.py
  project.env
  src/cart.ts
  src/outgoing_stock.ts
  src/ship_request.ts
  tests/conftest.py
  tests/test_outgoing_stock.py
  tests/test_ship_request.py
Labels: enhancement

#146 move shelf life from edit io to create io
  .prettierrc.json
  app/models/inbound_order.py
  app/models/io_allocate_product.py
  app/static/js/inbound_order.js
  app/templates/inbound_order/add.html
  app/templates/inbound_order/edit.html
  app/views/inbound_order.py
  migrations/versions/88e0268dc5fd_add_shelf_life_to_allocate_table.py
  src/inbound_order.ts
  tests/test_inbound_order.py
Labels: bug

#148 new groups
  app/__init__.py
  app/commands/__init__.py
  app/forms/product.py
  app/models/product.py
  app/schema/__init__.py
  app/schema/product.py
  app/static/js/cart.js
  app/static/js/group.js
  app/static/js/product.js
  app/templates/group_for_product/groups_for_product.html
  app/templates/master_group/master_groups.html
  app/templates/master_group_for_product/master_groups_for_product.html
  app/templates/product/add.html
  app/templates/product/edit.html
  app/templates/product/products.html
  app/templates/sidebar.html
  app/templates/stock_target_group/add.html
  app/templates/stock_target_group/edit.html
  app/templates/stock_target_group/stock_target_groups.html
  app/views/__init__.py
  app/views/group.py
  app/views/product.py
  migrations/versions/453643ac6064_unrequired_fields_for_product.py
  src/cart.ts
  src/group.ts
  src/product.ts
  tests/conftest.py
  tests/test_groups.py
  tests/test_products.py
Labels: bug, enhancement

#149 fix display edit product group
  app/static/js/product.js
  app/views/product.py
  src/product.ts
Labels: bug

#150 fix product sort by group
  app/static/js/product.js
  app/templates/product/products.html
  app/views/product.py
  src/product.ts
Labels: bug

#152 product-show-stocks-own-by-me
  app/static/js/inbound_order.js
  app/static/js/product.js
  app/templates/inbound_order/inbound_orders.html
  app/templates/product/products.html
  app/views/inventory.py
  app/views/product.py
  src/inbound_order.ts
  src/product.ts
Labels: enhancement

#154 sales rep locker
  app/commands/__init__.py
  app/forms/user.py
  app/models/cart.py
  app/models/ship_request.py
  app/models/store.py
  app/static/js/cart.d.ts
  app/static/js/cart.js
  app/static/js/user.js
  app/templates/cart.html
  app/templates/store_category/store_categories.html
  app/templates/user/add.html
  app/templates/user/view.html
  app/views/cart.py
  app/views/user.py
  app/views/warehouse.py
  config.py
  migrations/versions/12adaec72d3b_cascade_delete_to_ship_request_cart.py
  migrations/versions/c2b418abcde8_user_foreign_key_to_store.py
  src/cart.ts
  src/user.ts
  tests/conftest.py
  tests/test_cart.py
  tests/test_devision.py
  tests/test_warehouse.py
  tests/utils.py
Labels: enhancement

#158 delete product type from modals, rename quantity label
  app/static/js/product.js
  app/templates/product/adjust.html
  app/templates/product/view.html
  src/product.ts
Labels: bug

#163 shelf life not obligatory at create
  app/static/js/inbound_order.js
  app/static/js/product.js
  app/templates/inbound_order/edit.html
  app/views/inbound_order.py
  src/inbound_order.ts
Labels: bug

#157 fix edit, delete only one group in groups options.
  app/static/js/base.js
  app/static/js/user.js
  app/templates/base.html
  src/base.ts
  src/user.ts
Labels: bug

#179 added notification for decline action
  app/models/request_share.py
  app/static/js/request_share.js
  app/templates/email/request_share.html
  app/templates/request_share/request_shares.html
  app/views/product.py
  app/views/request_share.py
  migrations/versions/20bd2dd3dab1_add_order_numb_to_share_request.py
  src/request_share.ts
Labels: enhancement

#153 upload csv files
  app/__init__.py
  app/forms/__init__.py
  app/forms/product.py
  app/models/product.py
  app/models/ship_request.py
  app/schema/product.py
  app/static/css/styles.css
  app/static/js/cart.js
  app/static/js/outgoing_stock.js
  app/static/js/pickup_order.js
  app/static/js/product.js
  app/static/js/ship_request.js
  app/templates/cart.html
  app/templates/outgoing_stock/edit.html
  app/templates/outgoing_stock/view.html
  app/templates/pickup_order/view.html
  app/templates/product/add.html
  app/templates/product/edit.html
  app/templates/product/products.html
  app/templates/product/upload.html
  app/templates/product/view.html
  app/templates/ship_request/view.html
  app/templates/sidebar.html
  app/views/product.py
  migrations/versions/307d8f87cd33_product_name_to_str_128_and_unique_name.py
  migrations/versions/65f05d8db5e6_return_regular_and_retail_prices.py
  migrations/versions/6740fcf55222_product_name_to_str_256_and_descrition_.py
  poetry.lock
  project.env
  pyproject.toml
  src/cart.ts
  src/outgoing_stock.ts
  src/pickup_order.ts
  src/product.ts
  src/ship_request.ts
  tests/conftest.py
  tests/test_products.py
  tests/test_users.py
Labels: enhancement

#184 Andrii/feature/thumbnail image
  app/forms/product.py
  app/static/js/product.js
  app/templates/product/add.html
  app/views/product.py
  src/product.ts
  tests/test_products.py
Labels: enhancement

#186 full picture to products
  app/static/css/styles.css
  app/static/js/base.js
  app/static/js/incoming_stock.js
  app/static/js/product.js
  app/templates/base.html
  app/templates/outgoing_stock/edit.html
  app/templates/pickup_order/edit.html
  app/templates/product/adjust.html
  app/templates/product/edit.html
  app/templates/product/image.html
  app/templates/product/products.html
  app/templates/product/request_share.html
  app/templates/product/ship.html
  app/templates/product/view.html
  app/views/product.py
  src/base.ts
  src/incoming_stock.ts
  src/product.ts
  src/styles.css
Labels: enhancement

#195 fix available quantity for ship request product
  app/static/css/styles.css
  app/static/js/base.js
  app/static/js/cart.js
  app/static/js/inbound_order.js
  app/static/js/outgoing_stock.js
  app/static/js/product.js
  app/static/js/ship_request.js
  app/templates/outgoing_stock/edit.html
  app/templates/outgoing_stock/view.html
  app/templates/product/ship.html
  app/templates/ship_request/view.html
  src/base.ts
  src/cart.ts
  src/inbound_order.ts
  src/outgoing_stock.ts
  src/product.ts
  src/ship_request.ts
Labels: bug

#193 finished date for share request
  app/models/inbound_order.py
  app/models/request_share.py
  app/templates/request_share/request_shares.html
  app/views/request_share.py
  migrations/versions/901749b97d51_finished_date_to_share_request.py
Labels: enhancement

#183 adjust product without warehouses
  app/__init__.py
  app/forms/__init__.py
  app/forms/product.py
  app/models/__init__.py
  app/models/adjust.py
  app/models/adjusts_group_qty.py
  app/models/product.py
  app/schema/__init__.py
  app/schema/adjust.py
  app/static/js/adjust.d.ts
  app/static/js/adjust.js
  app/static/js/product.js
  app/templates/adjust/adjusts.html
  app/templates/adjust/view.html
  app/templates/product/adjust.html
  app/templates/sidebar.html
  app/views/__init__.py
  app/views/adjust.py
  app/views/product.py
  migrations/versions/70be3f9700a9_add_adjust.py
  src/adjust.ts
  src/product.ts
  webpack.config.js
Labels: bug
